// Gulper Aquarium — bakes the greedy floor tiling of layout.js's raster layers into baked.js (node, no three):
//   node src/world/stages/aquarium/bake-tiles.mjs
// layout.js reuses a baked layer only while its fingerprint matches (geo.js layer()), so a stale bake costs load time,
// never correctness. Run it after any change to the layout's pieces or regions (check-maps' output stays the same).
import fs from 'node:fs';
globalThis.__AQ_REGEN = true;
const { BAKE_OUT } = await import('./geo.js');
await import('./layout.js');
const keys = Object.keys(BAKE_OUT).sort();
const lines = keys.map((k) => `  ${JSON.stringify(k)}: { sig: ${JSON.stringify(BAKE_OUT[k].sig)}, r: [${BAKE_OUT[k].r.map((r) => '[' + r.join(',') + ']').join(',')}] },`);
const out = `// Gulper Aquarium — the baked tile cache (generated by bake-tiles.mjs; do not edit). ${keys.length} layers.\nexport const BAKED = {\n${lines.join('\n')}\n};\n`;
fs.writeFileSync(new URL('./baked.js', import.meta.url), out);
console.log('baked', keys.map((k) => `${k} ${BAKE_OUT[k].r.length}`).join(', '));
